# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  github_client_id: 714d82c50ef53a45bf0b
  github_client_secret: 8a9890bca0d20eaac690b1d62b888848ef848447

development:
  <<: *default
  secret_key_base: bd9f680a037e84ba72817b45a3fd83110fcbc59aab7ce0b9282b347d617355a132fcb6ba1d2989ba672bd7644758f39ea3c80d033814d4bf7586e495951fa459

test:
  <<: *default
  secret_key_base: 7af91855ba9e13496519ee10d7bbe36fd24bef9fb2130569369f7889b2bc26a7b3eb82ffe698d7b3df0fea6c51336ee5a72ee9515dc5f2499ac38dcbae4443c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
